{
    "_Type": "Action.Type.Filter",
    "PageToOpen": "/SAPAssetManager/Pages/Crew/FSMS4CrewFilter.page",
    "Filterable": "#Page:FSMS4CrewPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}