{
	"_Type": "Action.Type.Filter",
	"PageToOpen": "/SAPAssetManager/Pages/OnlineSearch/OnlineSearchCriteriaNotifications.page",
	"Filterable": "#Page:OnlineSearchNotificationsList/#Control:SectionedTable"
}