{
    "Target": {
        "EntitySet": "PhysicalInventoryDocItems",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "{@odata.readLink}"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}