{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/EWM/WarehouseOrders/WarehouseOrderSearchFilter.page",
    "Filterable" : "#Page:WarehouseOrdersListPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}