{
	"PageToOpen": "/SAPAssetManager/Pages/EWM/Fetch/FetchDocumentsOnline.page",
    "PageMetadata": "/SAPAssetManager/Rules/EWM/Fetch/FetchDocumentsOnlinePageMetadata.js",
    "_Type": "Action.Type.Navigation",
    "ModalPage": true
}