{
   "UploadCategories":
  [
    "OnEWMDocsOnly"
  ],
   "Service" : "/SAPAssetManager/Services/AssetManager.service",
   "_Type": "Action.Type.OfflineOData.Upload",
   "OnSuccess" : "/SAPAssetManager/Rules/EWM/Fetch/FetchErrorDownloadDocuments.js",
   "OnFailure": "/SAPAssetManager/Rules/EWM/Fetch/OnUploadFailure.js",
   "ActionResult": {
      "_Name": "result"
   } 
}
