{
    "Message": "$(L,download_progress)",
    "Animated": true,
    "_Type": "Action.Type.ProgressBanner",
    "OnSuccess": "/SAPAssetManager/Rules/PushNotifications/PushNotificationsDownloadProgressBannerOnSuccess.js"
}