{
	"PageToOpen": "/SAPAssetManager/Pages/FL/ReturnsByProduct/EDT/FLPBulkWOUpdate.page",
	"_Type": "Action.Type.Navigation",
	"PageMetadata": "/SAPAssetManager/Rules/FL/ReturnsByProduct/BulkUpdate/BulkFLPPageMetadataGenerator.js",
	"ModalPage": true,
	"ModalPageFullscreen": true
}