{
    "_Type": "Action.Type.CheckRequiredFields",
    "OnFailure": "/SAPAssetManager/Rules/Common/UpdateRequiredFailed.js",
    "OnSuccess": "/SAPAssetManager/Rules/ServiceConfirmations/CreateUpdate/ServiceConfirmationOnCommit.js",
    "RequiredFields": "/SAPAssetManager/Rules/ServiceConfirmations/CreateUpdate/ServiceConfirmationRequiredFields.js",
    "ValidationRule": "/SAPAssetManager/Rules/Common/Validation/TechnicalObjectCreateUpdateValidation.js"
}