{
	"_Type": "Action.Type.Navigation",
	"PageToOpen": "/SAPAssetManager/Rules/ServiceOrders/ServiceItems/ServiceItemDetailsPageToOpen.js",
	"PageMetadata": "/SAPAssetManager/Rules/ServiceOrders/ServiceItems/ServiceItemDetailsPageMetadata.js"
}