{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/WorkOrders/Meter/Periodic/RoutesListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/Meter/Periodic/RoutesPageMetadata.js"
}