{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/Inventory/Inbound/InboundSearchFilter.page",
    "Filterable" : "#Page:InboundDeliveryDetailPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}

