{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Notifications/RelatedNotificationsDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/Notifications/RelatedNotificationDetailsPageMetadata.js"
}