{
    "_Type": "Action.Type.Navigation",
    "PageToOpen": "/SAPAssetManager/Pages/FL/PackContainers/ReadyToPack/FLReadyToPackDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/FL/ReadyToPack/FLReadyToPackDetailsPageMetadata.js"
}