{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Documents/DocumentsBDSListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/Documents/DocumentsPageMetadata.js"
}
