{
	"_Type": "Action.Type.Navigation",
	"ModalPage": true,
	"PageToOpen": "/SAPAssetManager/Pages/Documents/DownloadDocuments.page",
	"PageMetadata": "/SAPAssetManager/Rules/Documents/DownloadDocuments/GenerateDocumentsPage.js"
}