{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/FL/Voyages/VoyagesSearchFilter.page",
    "Filterable" : "#Page:VoyagesListPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}