{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Crew/Vehicle/VehicleDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/Crew/Vehicles/VehicleDetailsPageMetadata.js"
}