{
  "PopoverItems":
	[{
 		"Title": "$(L,add_order)",
 		"OnPress" : "/SAPAssetManager/Rules/WorkOrders/FollowUpWorkOrderCreateNav.js",
		"Visible": "/SAPAssetManager/Rules/UserAuthorizations/WorkOrders/EnableWorkOrderCreateFromWorkOrder.js"
 	},
	{
		"Title": "$(L,add_operation)",
		"OnPress" : "/SAPAssetManager/Rules/WorkOrders/Operations/CreateUpdate/WorkOrderOperationCreateNav.js",
		"Visible": "/SAPAssetManager/Rules/UserAuthorizations/WorkOrders/EnableOperationCreate.js"
	},
	{
		"Title": "$(L,install_meter)",
		"OnPress" : "/SAPAssetManager/Rules/Meter/CreateUpdate/MeterInstallUpdateNav.js",
		"Visible": "/SAPAssetManager/Rules/WorkOrders/Meter/Details/AllowMeterCreate.js"
	},
	{
		"Title" : "$(L,add_part)",
		"OnPress" : "/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateNav.js",
		"Visible": "/SAPAssetManager/Rules/UserAuthorizations/WorkOrders/EnableWorkOrderEdit.js"
	},
	{
		"Title" : "$(L, add_note)",
		"OnPress" : "/SAPAssetManager/Rules/Notes/NoteCreateNav.js",
		"Visible": "/SAPAssetManager/Rules/UserAuthorizations/WorkOrders/EnableWorkOrderEdit.js"
	},
	{
		"Title": "$(L,add_notification)",
		"OnPress" : "/SAPAssetManager/Rules/WorkOrders/WorkOrderNotificationCreateNav.js",
		"Visible": "/SAPAssetManager/Rules/UserAuthorizations/Notifications/EnableNotificationCreateFromWorkOrder.js"
	},
	{
		"Title" : "$(L,add_reminder)",
		"OnPress" : "/SAPAssetManager/Rules/Reminders/ReminderCreateNav.js",
		"Visible": "/SAPAssetManager/Rules/UserAuthorizations/WorkOrders/EnableWorkOrderEdit.js"
	},
	{
		"Title": "$(L, add_smartform)",
		"Visible": "/SAPAssetManager/Rules/Forms/FSM/AddSmartForm/IsAddSmartFormButtonVisible.js",
		"OnPress": "/SAPAssetManager/Actions/Forms/AddSmartFormPageNav.action"
	},
	{
		"Title": "$(L,take_readings)",
		"OnPress": "/SAPAssetManager/Rules/Measurements/Points/MeasuringPointsDataEntryNavWrapper.js",
		"Visible":"/SAPAssetManager/Rules/Measurements/Points/MeasuringPointsTakeReadingsIsVisible.js"
	},
	{
 		"Title": "$(L,add_expense)",
 		"OnPress" : "/SAPAssetManager/Rules/Expense/CreateUpdate/ExpenseCreateNav.js",
		"Visible":  "/SAPAssetManager/Rules/Expense/CreateUpdate/IsAllowedExpenseCreate.js"
 	},
	{
		"Title": "$(L,add_mileage)",
		"OnPress": "/SAPAssetManager/Rules/ServiceOrders/Mileage/MileageAddNavCheckOnlyUnsavedChanges.js",
		"Visible": "/SAPAssetManager/Rules/ServiceOrders/Mileage/MileageAddIsEnabled.js"
	},
	{
		"Title": "$(L,confirmation_create_title)",
		"OnPress": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/ConfirmationCreateFromWONav.js",
		"Visible": "/SAPAssetManager/Rules/Confirmations/CreateUpdate/ConfirmationCreateFromWOIsEnabled.js"
	},
	{
		"Title": "$(L,sdf_add_form)",
		"OnPress": "/SAPAssetManager/Actions/Forms/SDF/FormCreateUpdateNav.action",
		"Visible": "/SAPAssetManager/Rules/Forms/SDF/SDFCreateEnabled.js"
	},
	{
		"Title": "$(L,generate_service_report)",
		"OnPress": "/SAPAssetManager/Rules/PDF/PDFGenerate.js",
		"Visible": "/SAPAssetManager/Rules/PDF/IsPDFAllowedForOrder.js"
	},
	{
		"Title": "$(L,add_support)",
		"OnPress": "/SAPAssetManager/Rules/ConfirmationScenarios/CooperationConfirmationNavWrapper.js",
		"Visible": "/SAPAssetManager/Rules/ConfirmationScenarios/CooperationIsEnabledForWorkOrder.js"
	},
	{
		"Title": "$(L,add_double_check)",
		"OnPress": "/SAPAssetManager/Rules/ConfirmationScenarios/DoubleCheckConfirmationNavWrapper.js",
		"Visible": "/SAPAssetManager/Rules/ConfirmationScenarios/DoubleCheckIsEnabledForWorkOrder.js"
	}],
	"_Type": "Action.Type.PopoverMenu"
}