{
	"_Type": "Action.Type.Navigation",
	"PageToOpen" : "/SAPAssetManager/Pages/FL/WorkOrders/FLProductDetails.page",
	"PageMetadata": "/SAPAssetManager/Rules/FL/WorkOrders/Products/Details/FLProductDetailsPageMetadata.js"
}
