{
    "_Type": "Action.Type.Navigation",
    "PageToOpen": "/SAPAssetManager/Pages/Notes/BPNotesListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/Notes/List/BPNotesListViewPageMetadata.js"
}