{
	"_Type": "Action.Type.RestService.SendRequest",
	"Target": {
		"Service": "/SAPAssetManager/Services/OnlineAssetManager.service",
		"Path": "/OauthTokens(ParameterGroup='NONE',ParameterName='ACCESS_TOKEN',RFCDestination='NONE')",
		"RequestProperties": {
			"Method": "PATCH",
			"Body": {
				"AccessToken": "",
				"RefreshToken": "",
				"ExpiresIn": ""
			},
			"Headers": {
				"Accept": "application/json",
				"Content-Type": "application/json"
			}
		}
  	}
}