{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/FL/Containers/ContainersSearchFilter.page",
    "Filterable" : "#Page:ContainersListPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}