{
	"PopoverItems": [
		{
			"Title": "$(L, add_notification)",
			"Visible": "/SAPAssetManager/Rules/UserAuthorizations/Notifications/EnableNotificationCreate.js",
			"OnPress": "/SAPAssetManager/Rules/WCM/QAB/WCMQABCreateNotification.js"
		},
		{
			"Title": "$(L, issue_approvals)",
			"OnPress": "/SAPAssetManager/Actions/WCM/Approvals/ApprovalsListViewNav.action"
		},
		{
			"Title": "$(L,sdf_add_form)",
			"OnPress": "/SAPAssetManager/Actions/Forms/SDF/FormCreateUpdateNav.action",
			"Visible": "/SAPAssetManager/Rules/Forms/SDF/SDFCreateEnabled.js"
		}
	],
	"_Type": "Action.Type.PopoverMenu"
}