{
	"PageToOpen": "/SAPAssetManager/Pages/Inventory/IssueOrReceipt/BulkUpdate/BulkIssueOrReceiptGenericFieldsCreate.page",
	"_Type": "Action.Type.Navigation",
	"ModalPage": true,
	"ModalPageFullscreen": true
}
