{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Rules/FunctionalLocation/FunctionalLocationDetailsPageToOpen.js",
    "PageMetadata": "/SAPAssetManager/Rules/FunctionalLocation/FunctionalLocationDetailsPageMetadata.js"
}
