{
    "PopoverItems": 
    [{
        "Title": "/SAPAssetManager/Rules/QAB/GetAddOrderButtonTitle.js",
        "OnPress": "/SAPAssetManager/Rules/WorkOrders/CreateUpdate/WorkOrderCreateNav.js",
        "Visible" : "/SAPAssetManager/Rules/FunctionalLocation/WorkOrderIsSamePlanningPlant.js"
    },
    {
        "Title": "$(L,add_notification)",
        "OnPress": "/SAPAssetManager/Rules/Notifications/CreateUpdate/NotificationCreateChangeSetNav.js",
        "Visible" : "/SAPAssetManager/Rules/FunctionalLocation/NotificationIsSamePlanningPlant.js"
    },
    {
        "Title": "/SAPAssetManager/Rules/Measurements/Points/MeasuringPointTakeReadingsButtonText.js",
        "Visible": "/SAPAssetManager/Rules/Equipment/EquipmentTakeReadingIsVisible.js",
        "OnPress": "/SAPAssetManager/Rules/Measurements/Points/MeasuringPointsDataEntryNavWrapper.js"
        
    },
    {
        "Title": "$(L,installation)",
        "Visible": "/SAPAssetManager/Rules/Equipment/Installation/EquipmentInstallationVisible.js",
        "OnPress": "/SAPAssetManager/Actions/Equipment/Installation/EquipmentInstallationNav.action"
    },
    {
        "Title": "$(L,dismantle)",
        "OnPress": "/SAPAssetManager/Actions/Equipment/Uninstall/UninstallEquipmentNav.action",
        "Visible": "/SAPAssetManager/Rules/Equipment/Uninstall/UninstallVisible.js"
    },
    {
        "Title": "$(L,add_service_order)",
        "OnPress": "/SAPAssetManager/Rules/ServiceOrders/CreateUpdate/ServiceOrderCreateNav.js",
        "Visible": "/SAPAssetManager/Rules/ServiceOrders/CreateUpdate/IsS4ServiceOrderCreateEnabled.js"
    },
    {
        "Title": "$(L,add_service_request)",
        "OnPress": "/SAPAssetManager/Rules/ServiceOrders/CreateUpdate/ServiceRequestCreateNav.js",
        "Visible": "/SAPAssetManager/Rules/ServiceOrders/ServiceRequests/IsS4ServiceRequestCreateEnabled.js"
    },
    {
		"Title": "$(L,sdf_add_form)",
		"OnPress": "/SAPAssetManager/Actions/Forms/SDF/FormCreateUpdateNav.action",
		"Visible": "/SAPAssetManager/Rules/Forms/SDF/SDFCreateEnabled.js"
	}],
    "_Type": "Action.Type.PopoverMenu"
}