{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
      "EntitySet": "UserPreferences",
      "Service": "/SAPAssetManager/Services/AssetManager.service",
		  "ReadLink": ""
    },
    "Properties": {
      "PreferenceName": "",
      "PreferenceValue": ""
    },
	"OnSuccess": "/SAPAssetManager/Actions/Filter/FilterSettingsUpdatedSuccess.action"
}