{
	"Target":
	{
		"EntitySet" : "WorkOrderHistories",
		"Service" : "/SAPAssetManager/Services/AssetManager.service",
		"QueryOptions" : "$filter=sap.hasPendingChanges() and OrderId eq '{{#Property:OrderId}}' and ReferenceType eq 'P'"
	},
	"Headers":
	{
        "Transaction.Ignore": "true"
	},
    "_Type": "Action.Type.ODataService.DeleteEntity"
}