{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Notifications/NotificationItemTasksListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/Notifications/Item/Task/NotificationItemTasksPageMetadata.js"
}