{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Notifications/NotificationItemTaskDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/Notifications/Item/Task/NotificationItemTaskDetailsPageMetadata.js"
}