{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Notifications/NotificationItemsListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/Notifications/Item/NotificationItemsPageMetadata.js"
}