{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/EWM/InboundDelivery/InboundDeliverySearchFilter.page",
    "Filterable" : "#Page:InboundDeliveryList/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}