{
    "Actions": [
        "/SAPAssetManager/Rules/FL/PackedPackages/BulkUpdate/BulkFLPUpdate.js"
    ],
    "Target": {
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "_Type": "Action.Type.ODataService.ChangeSet"
}