{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target": {
        "EntitySet" : "S4ServiceOrderPartners",
        "Service" : "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties": {
        "ObjectID": "{ObjectID}",
        "HeaderID": "{ObjectID}",
        "ItemNo": "{ItemNo}"
    },
    "Headers": {
        "OfflineOData.RemoveAfterUpload": "/SAPAssetManager/Rules/Common/RemoveAfterUploadValue.js"
    },
    "CreateLinks": "/SAPAssetManager/Rules/BusinessPartners/S4/S4BusinessPartnerLinks.js"
}