{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Notifications/NotificationTasksListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/Notifications/Task/NotificationTasksPageMetadata.js"
}