{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Notifications/NotificationTaskDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/Notifications/Task/NotificationTaskDetailsPageMetadata.js"
}