{
    "Actions": [
        "/SAPAssetManager/Rules/Meter/CreateUpdate/OnCommit/CreateMeterReadings.js"
    ],
    "OnSuccess": "/SAPAssetManager/Rules/Meter/CreateUpdate/PromptReadingWrapper.js",
    "OnFailure" : "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnFailure.js",
    "Target": {
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "_Type": "Action.Type.ODataService.ChangeSet"
}
