{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/WorkOrders/InspectionLot/InspectionLotDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/WorkOrders/InspectionLot/InspectionLotDetailsPageMetadata.js"
}