{
	"PageToOpen": "/SAPAssetManager/Pages/Inventory/MaterialDocument/MaterialDocumentItemDetails.page",
	"_Type": "Action.Type.Navigation",
	"PageMetadata": "/SAPAssetManager/Rules/Inventory/MaterialDocumentItem/MaterialDocumentItemDetailsMetadata.js"
}