{
    "Properties":
    {
        "Status": "I0116"
    },
    "Headers":
    {
        "Transaction.Ignore": "true"
    },
    "Target":
    {
        "EntitySet": "MyEquipObjectStatuses",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "MyEquipObjectStatuses('{{#Property:Item/#Property:ReturnValue}}')"
    },
    "_Type": "Action.Type.ODataService.UpdateEntity"
}