{
    "Target": {
        "EntitySet": "ErrorArchive",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "QueryOptions":"/SAPAssetManager/Rules/Common/ErrorArchiveQueryOptions.js"
    },
    "OnSuccess": "/SAPAssetManager/Rules/ApplicationEvents/AfterErrorDiscard.js",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/DeleteEntityFailureMessage.action",
    "_Type": "Action.Type.ODataService.DeleteEntity",
    "ActionResult": {
        "_Name": "DiscardResult"
    }
}