{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/EWM/PhysicalInventory/WHPhysicalInventorySearchFilter.page",
    "Filterable" : "#Page:WHPhysicalInventoryListPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}