
{
    "_Type": "Action.Type.OpenBarcodeScanner",
    "OnSuccess": "/SAPAssetManager/Rules/EWM/PhysicalInventory/Count/BarcodeScanSuccess.js",
    "OnFailure": "/SAPAssetManager/Rules/Inventory/SerialNumbers/BarcodeScanFailure.js",
    "ActionResult": {
        "_Name": "BarcodeScanner"
    }
}