{
	"_Type": "Action.Type.OpenBarcodeScanner",
	"OnSuccess": "/SAPAssetManager/Rules/EWM/Inbound/Items/HandlingUnit/WHHandlingUnitNumberScanOnSuccess.js",
    "ActionResult": {
        "_Name": "BarcodeScanner"
    }
}
