{
	"_Type": "Action.Type.Navigation",
	"ModalPage": true,
	"PageToOpen": "/SAPAssetManager/Pages/EWM/Inbound/HandlingUnit/WHHandlingUnitMixedCreate.page",
	"PageMetadata": "/SAPAssetManager/Rules/EWM/Inbound/Items/HandlingUnit/WHHandlingUnitMixedCreatePageMetadata.js"
}