{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Equipment/Warranties/EquipmentWarrantiesListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/Equipment/Warranties/EquipmentWarrantiesListViewPageMetadata.js"
}
