{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/OnlineSearch/EquipmentListView.page",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : "  ",
    "PageMetadata": "/SAPAssetManager/Rules/OnlineSearch/Equipment/OnlineEquipmentListViewPageMetadata.js"
}
