{
	"_Type": "Action.Type.Navigation",
	"PageToOpen": "/SAPAssetManager/Pages/InspectionCharacteristics/InspectionCharacteristicDetails.page",
	"PageMetadata": "/SAPAssetManager/Rules/InspectionCharacteristics/InspectionCharacteristicDetailsPageMetadata.js"
}