{
    "PopoverItems":
    [
        {
            "Title": "$(L, add_operational_item)",
            "OnPress": "/SAPAssetManager/Rules/WCM/OperationalItems/Create/OperationalItemCreateNav.js",
            "Visible": "/SAPAssetManager/Rules/WCM/SafetyCertificates/Details/IsLotoCertificate.js"
        },
        {
            "Title": "$(L, add_notification)",
            "OnPress": "/SAPAssetManager/Rules/WCM/QAB/WCMQABCreateNotification.js",
            "Visible": "/SAPAssetManager/Rules/UserAuthorizations/Notifications/EnableNotificationCreate.js"
        },
        {
			"Title": "$(L,sdf_add_form)",
			"OnPress": "/SAPAssetManager/Actions/Forms/SDF/FormCreateUpdateNav.action",
			"Visible": "/SAPAssetManager/Rules/Forms/SDF/SDFCreateEnabled.js"
		}
    ],
    "_Type": "Action.Type.PopoverMenu"
}