{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Target":
	{
		"EntitySet" : "NotificationHistoryTexts",
		"Service" : "/SAPAssetManager/Services/AssetManager.service"
	},
    "Properties": {}
}
