{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Target": {
		"EntitySet": "MyNotifGeometries",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"Properties": {
		"ObjectType": "NO1",
		"ObjectKey": "/SAPAssetManager/Rules/Notifications/CreateUpdate/NotificationNumberPath.js",
		"NotificationNumber": "/SAPAssetManager/Rules/Notifications/CreateUpdate/NotificationNumberPath.js"
	},
	"Headers": {
        "OfflineOData.RemoveAfterUpload": "/SAPAssetManager/Rules/Common/RemoveAfterUploadValue.js",
		"Transaction.Ignore": "true",
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Notifications/CreateUpdate/NotificationNumberPath.js"
    },
	"RequestOptions": {
		"UnmodifiableRequest": true,
		"SendEmptyUpdate": true
	},
	"CreateLinks": [{
			"Property" : "Geometry",
			"Target":
			{
				"EntitySet" : "Geometries",
				"ReadLink" : "/SAPAssetManager/Rules/Geometries/GeometryReadLink.js"
			}
		}, 
		{
			"Property" : "NotifHeader",
			"Target":
			{
				"EntitySet" : "MyNotificationHeaders",
				"ReadLink" : "/SAPAssetManager/Rules/Notifications/CreateUpdate/NotificationReadLinkPath.js"
			}
		}
	],
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action"
}