{
	"_Type": "Action.Type.Navigation",
	"PageToOpen" : "/SAPAssetManager/Pages/FL/PackContainers/AssignToContainerListView.page",
	"PageMetadata": "/SAPAssetManager/Rules/FL/PackedPackages/FLPackedPackagesListViewPageMetadata.js" 
}

