{
    "_Type": "Action.Type.Navigation",
    "PageToOpen": "/SAPAssetManager/Pages/FL/PackContainers/PackedPackages/FLPackedPackagesDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/FL/PackedPackages/FLPackedPackagesDetailsPageMetadata.js"
}