{
	"_Type": "Action.Type.Navigation",
	"PageToOpen": "/SAPAssetManager/Pages/WCM/WorkPermits/WorkPermitDetails.page",
	"PageMetadata": "/SAPAssetManager/Rules/WCM/WorkPermits/WorkPermitDetailsPageMetadata.js"
}