{
	"_Type": "Action.Type.Navigation",
	"PageToOpen" : "/SAPAssetManager/Pages/FL/ReturnsByProduct/FLPProductDetails.page",
	"PageMetadata": "/SAPAssetManager/Rules/FL/ReturnsByProduct/FLPProductDetailsPageMetadata.js"
}
