{
  "_Type": "Action.Type.Filter",
  "PageToOpen": "/SAPAssetManager/Pages/FL/ReturnsByProduct/FLReturnsByProductFilter.page",
  "Filterable" : "#Page:FLReturnsbyProductListViewPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}
