{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"Target": {
		"EntitySet": "MyWorkOrderGeometries",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"Properties": {},
	"Headers": {
        "OfflineOData.RemoveAfterUpload": "/SAPAssetManager/Rules/Common/RemoveAfterUploadValue.js",
		"Transaction.Ignore": "true"
    },
	"RequestOptions": {
		"UnmodifiableRequest": true,
		"SendEmptyUpdate": true
	},
	"CreateLinks": [],
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action"
}