{
	"_Type" : "Action.Type.Filter",
	"PageToOpen": "/SAPAssetManager/Pages/ServiceQuotations/ServiceQuotationItemsFilter.page",
	"Filterable": "#Page:S4ServiceQuotationItems/#Control:SectionedTable",
	"ActionResult": {
		"_Name": "filterResult"
	}
}