{
    "_Type": "Action.Type.Navigation",
	"PageToOpen": "/SAPAssetManager/Pages/ServiceQuotations/ServiceQuotationItemDetails.page",
	"PageMetadata": "/SAPAssetManager/Rules/ServiceQuotations/Items/Details/ServiceQuotationItemDetailsPageMetadata.js"
}