{
    "_Type": "Action.Type.ODataService.CreateEntity",
    "Target": {
      "EntitySet": "MatDocItemSerialNums",
      "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "Properties": {
      "MatDocItem": "/SAPAssetManager/Rules/Parts/Issue/LineItem/PartIssueLineItemLocalID.js",
      "SerialNum": "/SAPAssetManager/Rules/Parts/Issue/SerialParts/SerialNumber.js",
      "UniversalItemId": "/SAPAssetManager/Rules/Parts/Issue/SerialParts/UniversalItemId.js"
    },
    "Headers": {
      "OfflineOData.RemoveAfterUpload": "/SAPAssetManager/Rules/Common/RemoveAfterUploadValue.js",
      "OfflineOData.TransactionID": "#ClientData/#Property:LocalMatDocId"
    },
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntityFailureMessage.action",
    "CreateLinks": [
      {
    "Property": "MatDocItem_Nav",
    "Target": {
      "EntitySet": "MaterialDocItems",
      "ReadLink": "pending_2"
    }
  }
  ],
    "OnSuccess":"/SAPAssetManager/Rules/Parts/Issue/SerialParts/SerialNumberUpdateStatus.js",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : " "
  }