{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Parts/OnlinePartDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/Parts/OnlinePartDetailsPageMetadata.js"
}
