{
    "CancelPendingActions": false,
    "OnSuccess": "/SAPAssetManager/Actions/Parts/PartsIssueMessage.action",
    "DismissModal": "Action.Type.ClosePage.Completed",
    "_Type": "Action.Type.ClosePage"
}