{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Notifications/NotificationActivitiesListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/Notifications/Activity/NotificationActivitiesPageMetadata.js"
}