{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Notifications/NotificationItemActivitiesListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/Notifications/Item/Activity/NotificationItemActivitiesPageMetadata.js"
}