{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/WorkOrders/Operations/OnlineWorkOrderOperationsListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/WorkOrders/Operations/OnlineWorkOrderOperationListPageMetadata.js"
}
