{
    "PopoverItems": [
        {
            "Title": "$(L,add_suboperation)",
            "OnPress": "/SAPAssetManager/Rules/SubOperations/CreateUpdate/SubOperationCreateNav.js",
            "Visible": "/SAPAssetManager/Rules/UserAuthorizations/WorkOrders/EnableSubOperation.js"
        },
        {
            "Title": "$(L,add_notification)",
            "Visible": "/SAPAssetManager/Rules/UserAuthorizations/Notifications/EnableNotificationCreateFromWorkOrderOperation.js",
            "OnPress" : "/SAPAssetManager/Rules/Operations/WorkOrderOperationNotificationCreateNav.js"
        },
        {
            "Title" : "$(L,add_part)",
            "OnPress" : "/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateNav.js",
            "Visible": "/SAPAssetManager/Rules/UserAuthorizations/WorkOrders/EnableWorkOrderEdit.js"

        },
        {
            "Title" : "$(L, add_note)",
            "OnPress": "/SAPAssetManager/Rules/Notes/NoteCreateNav.js",
            "Visible": "/SAPAssetManager/Rules/UserAuthorizations/WorkOrders/EnableWorkOrderEdit.js"
        },
        {
            "Title" : "$(L,record_results)",
            "OnPress": "/SAPAssetManager/Rules/InspectionCharacteristics/InspectionCharacteristicsDynamicPageNavWrapper.js",
            "Visible": "/SAPAssetManager/Rules/InspectionCharacteristics/Update/EnableRecordResultsFromOperationDetails.js"
        },
        {
            "Title": "$(L,add_attachment)",
            "OnPress": "/SAPAssetManager/Rules/Documents/Create/DocumentCreateBDSNav.js",
            "Visible": "/SAPAssetManager/Rules/Documents/DocumentAddFromOperationDetails.js"
        },
        {
            "Title": "$(L,add_expense)",
            "OnPress" : "/SAPAssetManager/Rules/Expense/CreateUpdate/ExpenseCreateNav.js",
            "Visible":  "/SAPAssetManager/Rules/Expense/CreateUpdate/IsAllowedExpenseCreate.js"
        },
        {
            "Title": "$(L,add_mileage)",
            "OnPress": "/SAPAssetManager/Rules/ServiceOrders/Mileage/MileageAddNavCheckOnlyUnsavedChanges.js",
            "Visible": "/SAPAssetManager/Rules/ServiceOrders/Mileage/MileageAddIsEnabled.js"
        },
        {
            "Title": "$(L, add_smartform)",
            "Visible": "/SAPAssetManager/Rules/Forms/FSM/AddSmartForm/IsAddSmartFormButtonVisible.js",
            "OnPress": "/SAPAssetManager/Actions/Forms/AddSmartFormPageNav.action"
        },
        {
            "Title": "$(L,take_readings)",
            "OnPress": "/SAPAssetManager/Rules/Measurements/Points/MeasuringPointsDataEntryNavWrapper.js",
            "Visible":"/SAPAssetManager/Rules/Measurements/Points/MeasuringPointsTakeReadingsIsVisible.js"
	    },
        {
            "Title": "$(L,sdf_add_form)",
            "OnPress": "/SAPAssetManager/Actions/Forms/SDF/FormCreateUpdateNav.action",
            "Visible": "/SAPAssetManager/Rules/Forms/SDF/SDFCreateEnabled.js"
	    },
        {
            "Title": "$(L,generate_service_report)",
            "OnPress": "/SAPAssetManager/Rules/PDF/PDFGenerate.js",
            "Visible": "/SAPAssetManager/Rules/PDF/IsPDFAllowedForOperation.js"
        },
        {
            "Title": "$(L,add_support)",
            "OnPress": "/SAPAssetManager/Rules/ConfirmationScenarios/CooperationConfirmationNavWrapper.js",
            "Visible": "/SAPAssetManager/Rules/ConfirmationScenarios/CooperationIsEnabledForWorkOrder.js"
        },
        {
            "Title": "$(L,add_double_check)",
            "OnPress": "/SAPAssetManager/Rules/ConfirmationScenarios/DoubleCheckConfirmationNavWrapper.js",
            "Visible": "/SAPAssetManager/Rules/ConfirmationScenarios/DoubleCheckIsEnabledForWorkOrder.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}