{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Rules/WorkOrders/Operations/Details/WorkOrderOperationDetailsPageToOpen.js",
    "PageMetadata": "/SAPAssetManager/Rules/WorkOrders/Operations/WorkOrderOperationDetailsPageMetadata.js"
}
