{
	"_Type": "Action.Type.Navigation",
	"PageToOpen": "/SAPAssetManager/Pages/Confirmations/Details/ConfirmationsDetailsScreen.page",
	"PageMetadata": "/SAPAssetManager/Rules/Confirmations/Details/ConfirmationsDetailsScreenPageMetadata.js"
}