{
	"_Type" : "Action.Type.Filter",
	"PageToOpen": "/SAPAssetManager/Pages/FL/WorkOrders/FLOrderResvItemsFilter.page",
	"Filterable": "#Page:FLWOResvItemsList/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResults"
    }
}