{
  "_Type": "Action.Type.Filter",
  "PageToOpen": "/SAPAssetManager/Pages/FL/WorkOrders/FLWorkOrdersFilter.page",
  "Filterable" : "#Page:FLWorkOrdersListViewPage/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}