{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Notifications/NotificationActivityDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/Notifications/Activity/NotificationActivityDetailsPageMetadata.js"
}