{
    "Actions": [
        "/SAPAssetManager/Rules/FL/PackedContainers/BulkUpdate/BulkFLUpdate.js"
    ],
    "Target": {
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "_Type": "Action.Type.ODataService.ChangeSet"
}