{
    "_Type": "Action.Type.Navigation",
    "PageToOpen": "/SAPAssetManager/Pages/FL/PackContainers/PackedContainers/FLPackedContainersDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/FL/PackedContainers/FLPackedContainersDetailsPageMetadata.js"
}