{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/ServiceOrders/ServiceItemsTableView.page",
    "ShowActivityIndicator" : true,
    "ActivityIndicatorText" : " ",
    "PageMetadata": "/SAPAssetManager/Rules/ServiceItems/ServiceItemsTableViewPageMetadata.js"
}
