{
    "_Type": "Action.Type.Navigation",
    "PageToOpen": "/SAPAssetManager/Pages/ServiceOrders/ServiceOrganization/ServiceOrganizationDetails.page",
    "PageMetadata": "/SAPAssetManager/Rules/ServiceOrders/ServiceOrganization/ServiceOrganizationDetailsPageMetadata.js"
}