{
	"_Type" : "Action.Type.Filter",
	"PageToOpen": "/SAPAssetManager/Pages/ServiceOrders/ServiceOrderFilter.page",
	"Filterable": "#Page:ServiceOrdersListViewPage/#Control:SectionedTable",
	"ActionResult": {
		"_Name": "filterResult"
	}
}