{
    "_Type": "Action.Type.OfflineOData.Close",
    "Service": "/ZEquinorSSAM/Services/DEST_SAM2511_PPROP.service",
    "Force": true,
    "ActionResult": {
        "_Name": "close"
    },
    "OnSuccess": "/ZEquinorSSAM/Actions/DEST_SAM2511_PPROP/Service/CloseOfflineSuccessMessage.action",
    "OnFailure": "/ZEquinorSSAM/Actions/DEST_SAM2511_PPROP/Service/CloseOfflineFailureMessage.action"
}