{
    "Service": "/ZEquinorSSAM/Services/DEST_SAM2511_PPROP.service",
    "DefiningRequests": [{
            "Name": "AcctIndicators",
            "Query": "AcctIndicators"
        },
        {
            "Name": "ActivityTypes",
            "Query": "ActivityTypes"
        },
        {
            "Name": "AddressCommunications",
            "Query": "AddressCommunications"
        },
        {
            "Name": "AddressDetSequences",
            "Query": "AddressDetSequences"
        },
        {
            "Name": "Addresses",
            "Query": "Addresses"
        },
        {
            "Name": "AddressesAtWork",
            "Query": "AddressesAtWork"
        },
        {
            "Name": "AddressesAtWorkComm",
            "Query": "AddressesAtWorkComm"
        },
        {
            "Name": "AddressGeocodes",
            "Query": "AddressGeocodes"
        },
        {
            "Name": "AnswerHeaders",
            "Query": "AnswerHeaders"
        },
        {
            "Name": "AnswerOptions",
            "Query": "AnswerOptions"
        },
        {
            "Name": "AppParameters",
            "Query": "AppParameters"
        },
        {
            "Name": "AssetCentralEquipmentIndicators",
            "Query": "AssetCentralEquipmentIndicators"
        },
        {
            "Name": "AssetCentralObjectLinks",
            "Query": "AssetCentralObjectLinks"
        },
        {
            "Name": "AttendanceTypes",
            "Query": "AttendanceTypes"
        },
        {
            "Name": "AutoCreateWarehouseTasks",
            "Query": "AutoCreateWarehouseTasks"
        },
        {
            "Name": "AutoPacks",
            "Query": "AutoPacks"
        },
        {
            "Name": "BlockingStatuses",
            "Query": "BlockingStatuses"
        },
        {
            "Name": "BOMHeaders",
            "Query": "BOMHeaders"
        },
        {
            "Name": "BOMItems",
            "Query": "BOMItems"
        },
        {
            "Name": "BPCategories",
            "Query": "BPCategories"
        },
        {
            "Name": "BPNoteTypes",
            "Query": "BPNoteTypes"
        },
        {
            "Name": "BusinessAreas",
            "Query": "BusinessAreas"
        },
        {
            "Name": "BusinessPartners",
            "Query": "BusinessPartners"
        },
        {
            "Name": "CategorizationSchemas",
            "Query": "CategorizationSchemas"
        },
        {
            "Name": "CatsTimesheetOverviewRows",
            "Query": "CatsTimesheetOverviewRows"
        },
        {
            "Name": "CatsTimesheets",
            "Query": "CatsTimesheets"
        },
        {
            "Name": "CatsTimesheetTexts",
            "Query": "CatsTimesheetTexts"
        },
        {
            "Name": "Characteristics",
            "Query": "Characteristics"
        },
        {
            "Name": "CharValueCodes",
            "Query": "CharValueCodes"
        },
        {
            "Name": "ChecklistAssessmentQuestions",
            "Query": "ChecklistAssessmentQuestions"
        },
        {
            "Name": "ChecklistBusObjects",
            "Query": "ChecklistBusObjects"
        },
        {
            "Name": "ChecklistTypes",
            "Query": "ChecklistTypes"
        },
        {
            "Name": "ClassCharacteristics",
            "Query": "ClassCharacteristics"
        },
        {
            "Name": "ClassCharacteristicValues",
            "Query": "ClassCharacteristicValues"
        },
        {
            "Name": "ClassDefinitions",
            "Query": "ClassDefinitions"
        },
        {
            "Name": "ClassTypes",
            "Query": "ClassTypes"
        },
        {
            "Name": "COActivityTypes",
            "Query": "COActivityTypes"
        },
        {
            "Name": "ConfirmationLongTexts",
            "Query": "ConfirmationLongTexts"
        },
        {
            "Name": "ConfirmationOverviewRows",
            "Query": "ConfirmationOverviewRows"
        },
        {
            "Name": "Confirmations",
            "Query": "Confirmations"
        },
        {
            "Name": "ConsequenceCategories",
            "Query": "ConsequenceCategories"
        },
        {
            "Name": "ConsequenceGroups",
            "Query": "ConsequenceGroups"
        },
        {
            "Name": "ConsequenceLikelihoodMaps",
            "Query": "ConsequenceLikelihoodMaps"
        },
        {
            "Name": "ConsequenceLikelihoods",
            "Query": "ConsequenceLikelihoods"
        },
        {
            "Name": "ConsequenceSeverities",
            "Query": "ConsequenceSeverities"
        },
        {
            "Name": "ControlKeys",
            "Query": "ControlKeys"
        },
        {
            "Name": "CostCenters",
            "Query": "CostCenters"
        },
        {
            "Name": "Countries",
            "Query": "Countries"
        },
        {
            "Name": "CrewListItems",
            "Query": "CrewListItems"
        },
        {
            "Name": "CrewLists",
            "Query": "CrewLists"
        },
        {
            "Name": "Currencies",
            "Query": "Currencies"
        },
        {
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "DefectClasses",
            "Query": "DefectClasses"
        },
        {
            "Name": "DeliveryPriorities",
            "Query": "DeliveryPriorities"
        },
        {
            "Name": "DetectionCatalogs",
            "Query": "DetectionCatalogs"
        },
        {
            "Name": "DetectionCodes",
            "Query": "DetectionCodes"
        },
        {
            "Name": "DetectionGroups",
            "Query": "DetectionGroups"
        },
        {
            "Name": "DigitalSignatureApplications",
            "Query": "DigitalSignatureApplications"
        },
        {
            "Name": "DigitalSignatureAuthGroups",
            "Query": "DigitalSignatureAuthGroups"
        },
        {
            "Name": "DigitalSignatureHeaders",
            "Query": "DigitalSignatureHeaders"
        },
        {
            "Name": "DigitalSignatureItems",
            "Query": "DigitalSignatureItems"
        },
        {
            "Name": "DigitalSignatureLinks",
            "Query": "DigitalSignatureLinks"
        },
        {
            "Name": "DigitalSignatureMethods",
            "Query": "DigitalSignatureMethods"
        },
        {
            "Name": "DigitalSignatureNotes",
            "Query": "DigitalSignatureNotes"
        },
        {
            "Name": "DigitalSignatureObjectConfigs",
            "Query": "DigitalSignatureObjectConfigs"
        },
        {
            "Name": "DigitalSignatureObjects",
            "Query": "DigitalSignatureObjects"
        },
        {
            "Name": "DigitalSignatureStrategies",
            "Query": "DigitalSignatureStrategies"
        },
        {
            "Name": "DigitalSignatureTypes",
            "Query": "DigitalSignatureTypes"
        },
        {
            "Name": "DistributionChannels",
            "Query": "DistributionChannels"
        },
        {
            "Name": "Divisions",
            "Query": "Divisions"
        },
        {
            "Name": "Documents",
            "Query": "Documents"
        },
        {
            "Name": "EAMChecklistLinks",
            "Query": "EAMChecklistLinks"
        },
        {
            "Name": "EAMOverallStatusConfigs",
            "Query": "EAMOverallStatusConfigs"
        },
        {
            "Name": "EAMOverallStatusSeqs",
            "Query": "EAMOverallStatusSeqs"
        },
        {
            "Name": "EanUpcs",
            "Query": "EanUpcs"
        },
        {
            "Name": "Effects",
            "Query": "Effects"
        },
        {
            "Name": "EmployeeAddresses",
            "Query": "EmployeeAddresses"
        },
        {
            "Name": "EmployeeCommunications",
            "Query": "EmployeeCommunications"
        },
        {
            "Name": "Employees",
            "Query": "Employees"
        },
        {
            "Name": "EquipmentBOMs",
            "Query": "EquipmentBOMs"
        },
        {
            "Name": "EquipmentCategories",
            "Query": "EquipmentCategories"
        },
        {
            "Name": "EquipObjectTypes",
            "Query": "EquipObjectTypes"
        },
        {
            "Name": "EquipTemplates",
            "Query": "EquipTemplates"
        },
        {
            "Name": "FileExtensions",
            "Query": "FileExtensions"
        },
        {
            "Name": "FldLogsContainerItems",
            "Query": "FldLogsContainerItems"
        },
        {
            "Name": "FldLogsContainerItemSrNos",
            "Query": "FldLogsContainerItemSrNos"
        },
        {
            "Name": "FldLogsContainerItemStatuses",
            "Query": "FldLogsContainerItemStatuses"
        },
        {
            "Name": "FldLogsContainers",
            "Query": "FldLogsContainers"
        },
        {
            "Name": "FldLogsContainerStatuses",
            "Query": "FldLogsContainerStatuses"
        },
        {
            "Name": "FldLogsCtnPackageIds",
            "Query": "FldLogsCtnPackageIds"
        },
        {
            "Name": "FldLogsCtnPkgPackingStatuses",
            "Query": "FldLogsCtnPkgPackingStatuses"
        },
        {
            "Name": "FldLogsHandlingDecisions",
            "Query": "FldLogsHandlingDecisions"
        },
        {
            "Name": "FldLogsHuDelItems",
            "Query": "FldLogsHuDelItems"
        },
        {
            "Name": "FldLogsHuDelSnItems",
            "Query": "FldLogsHuDelSnItems"
        },
        {
            "Name": "FldLogsInitRetProducts",
            "Query": "FldLogsInitRetProducts"
        },
        {
            "Name": "FldLogsOrderCategories",
            "Query": "FldLogsOrderCategories"
        },
        {
            "Name": "FldLogsPackageItems",
            "Query": "FldLogsPackageItems"
        },
        {
            "Name": "FldLogsPackageItemSrNos",
            "Query": "FldLogsPackageItemSrNos"
        },
        {
            "Name": "FldLogsPackages",
            "Query": "FldLogsPackages"
        },
        {
            "Name": "FldLogsPackagingTypes",
            "Query": "FldLogsPackagingTypes"
        },
        {
            "Name": "FldLogsPackCtnActWgtUOMs",
            "Query": "FldLogsPackCtnActWgtUOMs"
        },
        {
            "Name": "FldLogsPackCtnContainerItems",
            "Query": "FldLogsPackCtnContainerItems"
        },
        {
            "Name": "FldLogsPackCtnContainerPkgs",
            "Query": "FldLogsPackCtnContainerPkgs"
        },
        {
            "Name": "FldLogsPackCtnContainerVygs",
            "Query": "FldLogsPackCtnContainerVygs"
        },
        {
            "Name": "FldLogsPackCtnItemStatuses",
            "Query": "FldLogsPackCtnItemStatuses"
        },
        {
            "Name": "FldLogsPackCtnLocIDs",
            "Query": "FldLogsPackCtnLocIDs"
        },
        {
            "Name": "FldLogsPackCtnPkdCtns",
            "Query": "FldLogsPackCtnPkdCtns"
        },
        {
            "Name": "FldLogsPackCtnPkdPkgs",
            "Query": "FldLogsPackCtnPkdPkgs"
        },
        {
            "Name": "FldLogsPackCtnPkgItems",
            "Query": "FldLogsPackCtnPkgItems"
        },
        {
            "Name": "FldLogsPackCtnPkgVygs",
            "Query": "FldLogsPackCtnPkgVygs"
        },
        {
            "Name": "FldLogsPackCtnRdyPcks",
            "Query": "FldLogsPackCtnRdyPcks"
        },
        {
            "Name": "FldLogsPackCtnRdyPckSrNos",
            "Query": "FldLogsPackCtnRdyPckSrNos"
        },
        {
            "Name": "FldLogsPackCtnRdyPckVygs",
            "Query": "FldLogsPackCtnRdyPckVygs"
        },
        {
            "Name": "FldLogsPlants",
            "Query": "FldLogsPlants"
        },
        {
            "Name": "FldLogsRecommendedActions",
            "Query": "FldLogsRecommendedActions"
        },
        {
            "Name": "FldLogsRefDocTypes",
            "Query": "FldLogsRefDocTypes"
        },
        {
            "Name": "FldLogsReturnStatuses",
            "Query": "FldLogsReturnStatuses"
        },
        {
            "Name": "FldLogsShippingPoints",
            "Query": "FldLogsShippingPoints"
        },
        {
            "Name": "FldLogsShptItemStatuses",
            "Query": "FldLogsShptItemStatuses"
        },
        {
            "Name": "FldLogsSupprocs",
            "Query": "FldLogsSupprocs"
        },
        {
            "Name": "FldLogsVisualInspections",
            "Query": "FldLogsVisualInspections"
        },
        {
            "Name": "FldLogsVoyageMasters",
            "Query": "FldLogsVoyageMasters"
        },
        {
            "Name": "FldLogsVoyages",
            "Query": "FldLogsVoyages"
        },
        {
            "Name": "FldLogsVoyageStatusCodeTypes",
            "Query": "FldLogsVoyageStatusCodeTypes"
        },
        {
            "Name": "FldLogsVoyageTypeCodes",
            "Query": "FldLogsVoyageTypeCodes"
        },
        {
            "Name": "FldLogsWoProducts",
            "Query": "FldLogsWoProducts"
        },
        {
            "Name": "FldLogsWoProductSrNos",
            "Query": "FldLogsWoProductSrNos"
        },
        {
            "Name": "FldLogsWoResvItems",
            "Query": "FldLogsWoResvItems"
        },
        {
            "Name": "FldLogsWorkOrders",
            "Query": "FldLogsWorkOrders"
        },
        {
            "Name": "Fleets",
            "Query": "Fleets"
        },
        {
            "Name": "FormGroups",
            "Query": "FormGroups"
        },
        {
            "Name": "FormQuestions",
            "Query": "FormQuestions"
        },
        {
            "Name": "Forms",
            "Query": "Forms"
        },
        {
            "Name": "FormTemplateGroups",
            "Query": "FormTemplateGroups"
        },
        {
            "Name": "FormTemplateHeaders",
            "Query": "FormTemplateHeaders"
        },
        {
            "Name": "FormTemplateQuestions",
            "Query": "FormTemplateQuestions"
        },
        {
            "Name": "FSMFormAttachments",
            "Query": "FSMFormAttachments"
        },
        {
            "Name": "FSMFormElements",
            "Query": "FSMFormElements"
        },
        {
            "Name": "FSMFormInstances",
            "Query": "FSMFormInstances"
        },
        {
            "Name": "FSMFormTemplates",
            "Query": "FSMFormTemplates"
        },
        {
            "Name": "FSMObjectPicker",
            "Query": "FSMObjectPicker"
        },
        {
            "Name": "FuncLocCategories",
            "Query": "FuncLocCategories"
        },
        {
            "Name": "FuncLocLabels",
            "Query": "FuncLocLabels"
        },
        {
            "Name": "FuncLocStructInds",
            "Query": "FuncLocStructInds"
        },
        {
            "Name": "FuncLocTemplates",
            "Query": "FuncLocTemplates"
        },
        {
            "Name": "FunctionalLocationBOMs",
            "Query": "FunctionalLocationBOMs"
        },
        {
            "Name": "Geometries",
            "Query": "Geometries"
        },
        {
            "Name": "GeometryTypes",
            "Query": "GeometryTypes"
        },
        {
            "Name": "GISMapParameters",
            "Query": "GISMapParameters"
        },
        {
            "Name": "GLAccounts",
            "Query": "GLAccounts"
        },
        {
            "Name": "GlobalParameters",
            "Query": "GlobalParameters"
        },
        {
            "Name": "GuidedFlowHeaders",
            "Query": "GuidedFlowHeaders"
        },
        {
            "Name": "GuidedFlowStatusConfigs",
            "Query": "GuidedFlowStatusConfigs"
        },
        {
            "Name": "GuidedFlowStatusSeqs",
            "Query": "GuidedFlowStatusSeqs"
        },
        {
            "Name": "GuidedFlowSteps",
            "Query": "GuidedFlowSteps"
        },
        {
            "Name": "HandlingUnitItems",
            "Query": "HandlingUnitItems"
        },
        {
            "Name": "HandlingUnits",
            "Query": "HandlingUnits"
        },
        {
            "Name": "HandlingUnitTypes",
            "Query": "HandlingUnitTypes"
        },
        {
            "Name": "InboundDeliveries",
            "Query": "InboundDeliveries"
        },
        {
            "Name": "InboundDeliveryBatchSplits",
            "Query": "InboundDeliveryBatchSplits"
        },
        {
            "Name": "InboundDeliveryItems",
            "Query": "InboundDeliveryItems"
        },
        {
            "Name": "InboundDeliverySerials",
            "Query": "InboundDeliverySerials"
        },
        {
            "Name": "InspectionCatalogValuations",
            "Query": "InspectionCatalogValuations"
        },
        {
            "Name": "InspectionCharacteristicLongTexts",
            "Query": "InspectionCharacteristicLongTexts"
        },
        {
            "Name": "InspectionCharacteristics",
            "Query": "InspectionCharacteristics"
        },
        {
            "Name": "InspectionCharDependencies",
            "Query": "InspectionCharDependencies"
        },
        {
            "Name": "InspectionCharStatuses",
            "Query": "InspectionCharStatuses"
        },
        {
            "Name": "InspectionCodes",
            "Query": "InspectionCodes"
        },
        {
            "Name": "InspectionHistories",
            "Query": "InspectionHistories"
        },
        {
            "Name": "InspectionLotDocuments",
            "Query": "InspectionLotDocuments"
        },
        {
            "Name": "InspectionLots",
            "Query": "InspectionLots"
        },
        {
            "Name": "InspectionMethodDocuments",
            "Query": "InspectionMethodDocuments"
        },
        {
            "Name": "InspectionMethodLongTexts",
            "Query": "InspectionMethodLongTexts"
        },
        {
            "Name": "InspectionMethods",
            "Query": "InspectionMethods"
        },
        {
            "Name": "InspectionPoints",
            "Query": "InspectionPoints"
        },
        {
            "Name": "InspectionPointValuations",
            "Query": "InspectionPointValuations"
        },
        {
            "Name": "InspectionResultValuations",
            "Query": "InspectionResultValuations"
        },
        {
            "Name": "ItemCategories",
            "Query": "ItemCategories"
        },
        {
            "Name": "LAMCharacteristicValues",
            "Query": "LAMCharacteristicValues"
        },
        {
            "Name": "LAMObjectData",
            "Query": "LAMObjectData"
        },
        {
            "Name": "LAMOffsetTypes",
            "Query": "LAMOffsetTypes"
        },
        {
            "Name": "Languages",
            "Query": "Languages"
        },
        {
            "Name": "LinearReferencePatternHeaders",
            "Query": "LinearReferencePatternHeaders"
        },
        {
            "Name": "LinearReferencePatternItems",
            "Query": "LinearReferencePatternItems"
        },
        {
            "Name": "Locations",
            "Query": "Locations"
        },
        {
            "Name": "LongTextTemplates",
            "Query": "LongTextTemplates"
        },
        {
            "Name": "ManufacturerPartNumbers",
            "Query": "ManufacturerPartNumbers"
        },
        {
            "Name": "MarkedJobs",
            "Query": "MarkedJobs"
        },
        {
            "Name": "MasterInspectionCharLongTexts",
            "Query": "MasterInspectionCharLongTexts"
        },
        {
            "Name": "MasterInspectionChars",
            "Query": "MasterInspectionChars"
        },
        {
            "Name": "MatDocAttachments",
            "Query": "MatDocAttachments"
        },
        {
            "Name": "MatDocItemSerialNums",
            "Query": "MatDocItemSerialNums"
        },
        {
            "Name": "MaterialBatches",
            "Query": "MaterialBatches"
        },
        {
            "Name": "MaterialBatchStockSet",
            "Query": "MaterialBatchStockSet"
        },
        {
            "Name": "MaterialBOMs",
            "Query": "MaterialBOMs"
        },
        {
            "Name": "MaterialDocItems",
            "Query": "MaterialDocItems"
        },
        {
            "Name": "MaterialDocuments",
            "Query": "MaterialDocuments"
        },
        {
            "Name": "MaterialPlants",
            "Query": "MaterialPlants"
        },
        {
            "Name": "MaterialProjectStocks",
            "Query": "MaterialProjectStocks"
        },
        {
            "Name": "Materials",
            "Query": "Materials"
        },
        {
            "Name": "MaterialSales",
            "Query": "MaterialSales"
        },
        {
            "Name": "MaterialSLocs",
            "Query": "MaterialSLocs"
        },
        {
            "Name": "MaterialUOMs",
            "Query": "MaterialUOMs"
        },
        {
            "Name": "MaterialValuations",
            "Query": "MaterialValuations"
        },
        {
            "Name": "MaterialVendorConsignmentStocks",
            "Query": "MaterialVendorConsignmentStocks"
        },
        {
            "Name": "MeasurementDocumentLongTexts",
            "Query": "MeasurementDocumentLongTexts"
        },
        {
            "Name": "MeasurementDocuments",
            "Query": "MeasurementDocuments"
        },
        {
            "Name": "MeasuringPoints",
            "Query": "MeasuringPoints"
        },
        {
            "Name": "MeasuringPointTexts",
            "Query": "MeasuringPointTexts"
        },
        {
            "Name": "MobileClientSynchronizationSessions",
            "Query": "MobileClientSynchronizationSessions"
        },
        {
            "Name": "MobileStatusMappings",
            "Query": "MobileStatusMappings"
        },
        {
            "Name": "MovementReasons",
            "Query": "MovementReasons"
        },
        {
            "Name": "MovementTypes",
            "Query": "MovementTypes"
        },
        {
            "Name": "MovementTypeSpecialStocks",
            "Query": "MovementTypeSpecialStocks"
        },
        {
            "Name": "MovementTypeTcodes",
            "Query": "MovementTypeTcodes"
        },
        {
            "Name": "MovementTypeTexts",
            "Query": "MovementTypeTexts"
        },
        {
            "Name": "MyEAMWorkOrderHeaders",
            "Query": "MyEAMWorkOrderHeaders"
        },
        {
            "Name": "MyEAMWorkOrderOperations",
            "Query": "MyEAMWorkOrderOperations"
        },
        {
            "Name": "MyEquipClassCharValues",
            "Query": "MyEquipClassCharValues"
        },
        {
            "Name": "MyEquipClasses",
            "Query": "MyEquipClasses"
        },
        {
            "Name": "MyEquipDocuments",
            "Query": "MyEquipDocuments"
        },
        {
            "Name": "MyEquipGeometries",
            "Query": "MyEquipGeometries"
        },
        {
            "Name": "MyEquipLongTexts",
            "Query": "MyEquipLongTexts"
        },
        {
            "Name": "MyEquipments",
            "Query": "MyEquipments"
        },
        {
            "Name": "MyEquipObjectStatuses",
            "Query": "MyEquipObjectStatuses"
        },
        {
            "Name": "MyEquipPartners",
            "Query": "MyEquipPartners"
        },
        {
            "Name": "MyEquipSerialNumbers",
            "Query": "MyEquipSerialNumbers"
        },
        {
            "Name": "MyEquipSystemStatuses",
            "Query": "MyEquipSystemStatuses"
        },
        {
            "Name": "MyEquipUserStatuses",
            "Query": "MyEquipUserStatuses"
        },
        {
            "Name": "MyEquipWarranties",
            "Query": "MyEquipWarranties"
        },
        {
            "Name": "MyEquipWarrantyLongTexts",
            "Query": "MyEquipWarrantyLongTexts"
        },
        {
            "Name": "MyFuncLocClassCharValues",
            "Query": "MyFuncLocClassCharValues"
        },
        {
            "Name": "MyFuncLocClasses",
            "Query": "MyFuncLocClasses"
        },
        {
            "Name": "MyFuncLocDocuments",
            "Query": "MyFuncLocDocuments"
        },
        {
            "Name": "MyFuncLocGeometries",
            "Query": "MyFuncLocGeometries"
        },
        {
            "Name": "MyFuncLocLongTexts",
            "Query": "MyFuncLocLongTexts"
        },
        {
            "Name": "MyFuncLocObjectStatuses",
            "Query": "MyFuncLocObjectStatuses"
        },
        {
            "Name": "MyFuncLocPartners",
            "Query": "MyFuncLocPartners"
        },
        {
            "Name": "MyFuncLocSystemStatuses",
            "Query": "MyFuncLocSystemStatuses"
        },
        {
            "Name": "MyFuncLocUserStatuses",
            "Query": "MyFuncLocUserStatuses"
        },
        {
            "Name": "MyFunctionalLocations",
            "Query": "MyFunctionalLocations"
        },
        {
            "Name": "MyInventoryObjects",
            "Query": "MyInventoryObjects"
        },
        {
            "Name": "MyNotifActivityLongTexts",
            "Query": "MyNotifActivityLongTexts"
        },
        {
            "Name": "MyNotifDocuments",
            "Query": "MyNotifDocuments"
        },
        {
            "Name": "MyNotifGeometries",
            "Query": "MyNotifGeometries"
        },
        {
            "Name": "MyNotifHeaderLongTexts",
            "Query": "MyNotifHeaderLongTexts"
        },
        {
            "Name": "MyNotificationActivities",
            "Query": "MyNotificationActivities"
        },
        {
            "Name": "MyNotificationHeaders",
            "Query": "MyNotificationHeaders"
        },
        {
            "Name": "MyNotificationItemActivities",
            "Query": "MyNotificationItemActivities"
        },
        {
            "Name": "MyNotificationItemCauses",
            "Query": "MyNotificationItemCauses"
        },
        {
            "Name": "MyNotificationItems",
            "Query": "MyNotificationItems"
        },
        {
            "Name": "MyNotificationItemTasks",
            "Query": "MyNotificationItemTasks"
        },
        {
            "Name": "MyNotificationPartners",
            "Query": "MyNotificationPartners"
        },
        {
            "Name": "MyNotificationSales",
            "Query": "MyNotificationSales"
        },
        {
            "Name": "MyNotificationTasks",
            "Query": "MyNotificationTasks"
        },
        {
            "Name": "MyNotifItemActivityLongTexts",
            "Query": "MyNotifItemActivityLongTexts"
        },
        {
            "Name": "MyNotifItemCauseLongTexts",
            "Query": "MyNotifItemCauseLongTexts"
        },
        {
            "Name": "MyNotifItemLongTexts",
            "Query": "MyNotifItemLongTexts"
        },
        {
            "Name": "MyNotifItemTaskLongTexts",
            "Query": "MyNotifItemTaskLongTexts"
        },
        {
            "Name": "MyNotifTaskLongTexts",
            "Query": "MyNotifTaskLongTexts"
        },
        {
            "Name": "MyRoutePoints",
            "Query": "MyRoutePoints"
        },
        {
            "Name": "MyRoutes",
            "Query": "MyRoutes"
        },
        {
            "Name": "MyRouteStops",
            "Query": "MyRouteStops"
        },
        {
            "Name": "MyTechObjects",
            "Query": "MyTechObjects"
        },
        {
            "Name": "MyWorkOrderComponentLongTexts",
            "Query": "MyWorkOrderComponentLongTexts"
        },
        {
            "Name": "MyWorkOrderComponentMatDocs",
            "Query": "MyWorkOrderComponentMatDocs"
        },
        {
            "Name": "MyWorkOrderComponents",
            "Query": "MyWorkOrderComponents"
        },
        {
            "Name": "MyWorkOrderDocuments",
            "Query": "MyWorkOrderDocuments"
        },
        {
            "Name": "MyWorkOrderGeometries",
            "Query": "MyWorkOrderGeometries"
        },
        {
            "Name": "MyWorkOrderHeaderLongTexts",
            "Query": "MyWorkOrderHeaderLongTexts"
        },
        {
            "Name": "MyWorkOrderHeaders",
            "Query": "MyWorkOrderHeaders"
        },
        {
            "Name": "MyWorkOrderObjectLists",
            "Query": "MyWorkOrderObjectLists"
        },
        {
            "Name": "MyWorkOrderOperationCapacityRequirements",
            "Query": "MyWorkOrderOperationCapacityRequirements"
        },
        {
            "Name": "MyWorkOrderOperationLongTexts",
            "Query": "MyWorkOrderOperationLongTexts"
        },
        {
            "Name": "MyWorkOrderOperations",
            "Query": "MyWorkOrderOperations"
        },
        {
            "Name": "MyWorkOrderPartners",
            "Query": "MyWorkOrderPartners"
        },
        {
            "Name": "MyWorkOrderSales",
            "Query": "MyWorkOrderSales"
        },
        {
            "Name": "MyWorkOrderSubOperations",
            "Query": "MyWorkOrderSubOperations"
        },
        {
            "Name": "MyWorkOrderSubOpLongTexts",
            "Query": "MyWorkOrderSubOpLongTexts"
        },
        {
            "Name": "MyWorkOrderToolLongTexts",
            "Query": "MyWorkOrderToolLongTexts"
        },
        {
            "Name": "MyWorkOrderTools",
            "Query": "MyWorkOrderTools"
        },
        {
            "Name": "NotificationHistories",
            "Query": "NotificationHistories"
        },
        {
            "Name": "NotificationHistoryTexts",
            "Query": "NotificationHistoryTexts"
        },
        {
            "Name": "NotificationProcessingContexts",
            "Query": "NotificationProcessingContexts"
        },
        {
            "Name": "NotificationTypes",
            "Query": "NotificationTypes"
        },
        {
            "Name": "NotifPartnerDetProcs",
            "Query": "NotifPartnerDetProcs"
        },
        {
            "Name": "ObjectFormCategories",
            "Query": "ObjectFormCategories"
        },
        {
            "Name": "OnDemandObjects",
            "Query": "OnDemandObjects"
        },
        {
            "Name": "OrderActivityTypes",
            "Query": "OrderActivityTypes"
        },
        {
            "Name": "OrderTypePartners",
            "Query": "OrderTypePartners"
        },
        {
            "Name": "OrderTypes",
            "Query": "OrderTypes"
        },
        {
            "Name": "OutboundDeliveries",
            "Query": "OutboundDeliveries"
        },
        {
            "Name": "OutboundDeliveryBatchSplits",
            "Query": "OutboundDeliveryBatchSplits"
        },
        {
            "Name": "OutboundDeliveryItems",
            "Query": "OutboundDeliveryItems"
        },
        {
            "Name": "OutboundDeliverySerials",
            "Query": "OutboundDeliverySerials"
        },
        {
            "Name": "PartnerDetProcs",
            "Query": "PartnerDetProcs"
        },
        {
            "Name": "PartnerFunctions",
            "Query": "PartnerFunctions"
        },
        {
            "Name": "PhaseControlCodes",
            "Query": "PhaseControlCodes"
        },
        {
            "Name": "PhaseControlKeys",
            "Query": "PhaseControlKeys"
        },
        {
            "Name": "PhaseControls",
            "Query": "PhaseControls"
        },
        {
            "Name": "PhaseControlSystemMobileStatusMaps",
            "Query": "PhaseControlSystemMobileStatusMaps"
        },
        {
            "Name": "PhaseControlSystemStatuses",
            "Query": "PhaseControlSystemStatuses"
        },
        {
            "Name": "PhysicalInventoryDocHeaders",
            "Query": "PhysicalInventoryDocHeaders"
        },
        {
            "Name": "PhysicalInventoryDocItems",
            "Query": "PhysicalInventoryDocItems"
        },
        {
            "Name": "PhysicalInventoryDocItemSerials",
            "Query": "PhysicalInventoryDocItemSerials"
        },
        {
            "Name": "PhysicalInventoryStockTypes",
            "Query": "PhysicalInventoryStockTypes"
        },
        {
            "Name": "PlannerGroups",
            "Query": "PlannerGroups"
        },
        {
            "Name": "Plants",
            "Query": "Plants"
        },
        {
            "Name": "PMAuthorizationGroups",
            "Query": "PMAuthorizationGroups"
        },
        {
            "Name": "PMCatalogCodes",
            "Query": "PMCatalogCodes"
        },
        {
            "Name": "PMCatalogProfiles",
            "Query": "PMCatalogProfiles"
        },
        {
            "Name": "PMMobileStatuses",
            "Query": "PMMobileStatuses"
        },
        {
            "Name": "PMMobileStatusHistories",
            "Query": "PMMobileStatusHistories"
        },
        {
            "Name": "Priorities",
            "Query": "Priorities"
        },
        {
            "Name": "PrioritizationMaps",
            "Query": "PrioritizationMaps"
        },
        {
            "Name": "PrioritizationProfileLinks",
            "Query": "PrioritizationProfileLinks"
        },
        {
            "Name": "PrioritizationProfiles",
            "Query": "PrioritizationProfiles"
        },
        {
            "Name": "ProductionOrderComponents",
            "Query": "ProductionOrderComponents"
        },
        {
            "Name": "ProductionOrderHeaders",
            "Query": "ProductionOrderHeaders"
        },
        {
            "Name": "ProductionOrderItems",
            "Query": "ProductionOrderItems"
        },
        {
            "Name": "ProductionOrderOperations",
            "Query": "ProductionOrderOperations"
        },
        {
            "Name": "ProductionOrderSequences",
            "Query": "ProductionOrderSequences"
        },
        {
            "Name": "ProductionOrderSerials",
            "Query": "ProductionOrderSerials"
        },
        {
            "Name": "ProductionOrderTexts",
            "Query": "ProductionOrderTexts"
        },
        {
            "Name": "ProductStatistics",
            "Query": "ProductStatistics"
        },
        {
            "Name": "PRTCategories",
            "Query": "PRTCategories"
        },
        {
            "Name": "PRTControlKeys",
            "Query": "PRTControlKeys"
        },
        {
            "Name": "PurchaseGroups",
            "Query": "PurchaseGroups"
        },
        {
            "Name": "PurchaseOrderHeaderLongTexts",
            "Query": "PurchaseOrderHeaderLongTexts"
        },
        {
            "Name": "PurchaseOrderHeaders",
            "Query": "PurchaseOrderHeaders"
        },
        {
            "Name": "PurchaseOrderItems",
            "Query": "PurchaseOrderItems"
        },
        {
            "Name": "PurchaseOrderSerialNumbers",
            "Query": "PurchaseOrderSerialNumbers"
        },
        {
            "Name": "PurchaseOrganizations",
            "Query": "PurchaseOrganizations"
        },
        {
            "Name": "PurchaseRequisitionAcctAsgns",
            "Query": "PurchaseRequisitionAcctAsgns"
        },
        {
            "Name": "PurchaseRequisitionAddresses",
            "Query": "PurchaseRequisitionAddresses"
        },
        {
            "Name": "PurchaseRequisitionDocTypes",
            "Query": "PurchaseRequisitionDocTypes"
        },
        {
            "Name": "PurchaseRequisitionHeaders",
            "Query": "PurchaseRequisitionHeaders"
        },
        {
            "Name": "PurchaseRequisitionItems",
            "Query": "PurchaseRequisitionItems"
        },
        {
            "Name": "PurchaseRequisitionLongTexts",
            "Query": "PurchaseRequisitionLongTexts"
        },
        {
            "Name": "PurchaseRequisitionServMgmntHdrs",
            "Query": "PurchaseRequisitionServMgmntHdrs"
        },
        {
            "Name": "PurchaseRequisitionServMgmntItems",
            "Query": "PurchaseRequisitionServMgmntItems"
        },
        {
            "Name": "PurchaseRequisitionSrvAccctAsgns",
            "Query": "PurchaseRequisitionSrvAccctAsgns"
        },
        {
            "Name": "PurchaseRequisitionSrvLimitHdrs",
            "Query": "PurchaseRequisitionSrvLimitHdrs"
        },
        {
            "Name": "PurchaseRequisitionSrvLimitItems",
            "Query": "PurchaseRequisitionSrvLimitItems"
        },
        {
            "Name": "ReceivingPoints",
            "Query": "ReceivingPoints"
        },
        {
            "Name": "Regions",
            "Query": "Regions"
        },
        {
            "Name": "RejectionReasons",
            "Query": "RejectionReasons"
        },
        {
            "Name": "ReportTemplates",
            "Query": "ReportTemplates"
        },
        {
            "Name": "ReservationHeaders",
            "Query": "ReservationHeaders"
        },
        {
            "Name": "ReservationItems",
            "Query": "ReservationItems"
        },
        {
            "Name": "S4BPOrgs",
            "Query": "S4BPOrgs"
        },
        {
            "Name": "S4BPRelationships",
            "Query": "S4BPRelationships"
        },
        {
            "Name": "S4BPRoles",
            "Query": "S4BPRoles"
        },
        {
            "Name": "S4BPSalesAreas",
            "Query": "S4BPSalesAreas"
        },
        {
            "Name": "S4BusinessPartnerLongTexts",
            "Query": "S4BusinessPartnerLongTexts"
        },
        {
            "Name": "S4BusinessPartners",
            "Query": "S4BusinessPartners"
        },
        {
            "Name": "S4ContractDeterminations",
            "Query": "S4ContractDeterminations"
        },
        {
            "Name": "S4LongTextDeterminations",
            "Query": "S4LongTextDeterminations"
        },
        {
            "Name": "S4PartnerFunctions",
            "Query": "S4PartnerFunctions"
        },
        {
            "Name": "S4RejectionReasons",
            "Query": "S4RejectionReasons"
        },
        {
            "Name": "S4ServiceConfirmationDocuments",
            "Query": "S4ServiceConfirmationDocuments"
        },
        {
            "Name": "S4ServiceConfirmationItems",
            "Query": "S4ServiceConfirmationItems"
        },
        {
            "Name": "S4ServiceConfirmationLongTexts",
            "Query": "S4ServiceConfirmationLongTexts"
        },
        {
            "Name": "S4ServiceConfirmationPartners",
            "Query": "S4ServiceConfirmationPartners"
        },
        {
            "Name": "S4ServiceConfirmationRefObjHistories",
            "Query": "S4ServiceConfirmationRefObjHistories"
        },
        {
            "Name": "S4ServiceConfirmationRefObjHistoryTexts",
            "Query": "S4ServiceConfirmationRefObjHistoryTexts"
        },
        {
            "Name": "S4ServiceConfirmationRefObjs",
            "Query": "S4ServiceConfirmationRefObjs"
        },
        {
            "Name": "S4ServiceConfirmations",
            "Query": "S4ServiceConfirmations"
        },
        {
            "Name": "S4ServiceConfirmationTranHistories",
            "Query": "S4ServiceConfirmationTranHistories"
        },
        {
            "Name": "S4ServiceContractDocuments",
            "Query": "S4ServiceContractDocuments"
        },
        {
            "Name": "S4ServiceContractItems",
            "Query": "S4ServiceContractItems"
        },
        {
            "Name": "S4ServiceContractLongTexts",
            "Query": "S4ServiceContractLongTexts"
        },
        {
            "Name": "S4ServiceContractRefObjs",
            "Query": "S4ServiceContractRefObjs"
        },
        {
            "Name": "S4ServiceContracts",
            "Query": "S4ServiceContracts"
        },
        {
            "Name": "S4ServiceContractTranHistories",
            "Query": "S4ServiceContractTranHistories"
        },
        {
            "Name": "S4ServiceErrorMessages",
            "Query": "S4ServiceErrorMessages"
        },
        {
            "Name": "S4ServiceItems",
            "Query": "S4ServiceItems"
        },
        {
            "Name": "S4ServiceOrderDocuments",
            "Query": "S4ServiceOrderDocuments"
        },
        {
            "Name": "S4ServiceOrderLongTexts",
            "Query": "S4ServiceOrderLongTexts"
        },
        {
            "Name": "S4ServiceOrderPartners",
            "Query": "S4ServiceOrderPartners"
        },
        {
            "Name": "S4ServiceOrderRefObjHistories",
            "Query": "S4ServiceOrderRefObjHistories"
        },
        {
            "Name": "S4ServiceOrderRefObjHistoryTexts",
            "Query": "S4ServiceOrderRefObjHistoryTexts"
        },
        {
            "Name": "S4ServiceOrderRefObjs",
            "Query": "S4ServiceOrderRefObjs"
        },
        {
            "Name": "S4ServiceOrders",
            "Query": "S4ServiceOrders"
        },
        {
            "Name": "S4ServiceOrderTranHistories",
            "Query": "S4ServiceOrderTranHistories"
        },
        {
            "Name": "S4ServiceQuotationDocuments",
            "Query": "S4ServiceQuotationDocuments"
        },
        {
            "Name": "S4ServiceQuotationItems",
            "Query": "S4ServiceQuotationItems"
        },
        {
            "Name": "S4ServiceQuotationLongTexts",
            "Query": "S4ServiceQuotationLongTexts"
        },
        {
            "Name": "S4ServiceQuotationPartners",
            "Query": "S4ServiceQuotationPartners"
        },
        {
            "Name": "S4ServiceQuotationRefObjHistories",
            "Query": "S4ServiceQuotationRefObjHistories"
        },
        {
            "Name": "S4ServiceQuotationRefObjHistoryTexts",
            "Query": "S4ServiceQuotationRefObjHistoryTexts"
        },
        {
            "Name": "S4ServiceQuotationRefObjs",
            "Query": "S4ServiceQuotationRefObjs"
        },
        {
            "Name": "S4ServiceQuotations",
            "Query": "S4ServiceQuotations"
        },
        {
            "Name": "S4ServiceQuotationTranHistories",
            "Query": "S4ServiceQuotationTranHistories"
        },
        {
            "Name": "S4ServiceRequestDocuments",
            "Query": "S4ServiceRequestDocuments"
        },
        {
            "Name": "S4ServiceRequestLongTexts",
            "Query": "S4ServiceRequestLongTexts"
        },
        {
            "Name": "S4ServiceRequestPartners",
            "Query": "S4ServiceRequestPartners"
        },
        {
            "Name": "S4ServiceRequestRefObjHistories",
            "Query": "S4ServiceRequestRefObjHistories"
        },
        {
            "Name": "S4ServiceRequestRefObjHistoryTexts",
            "Query": "S4ServiceRequestRefObjHistoryTexts"
        },
        {
            "Name": "S4ServiceRequestRefObjs",
            "Query": "S4ServiceRequestRefObjs"
        },
        {
            "Name": "S4ServiceRequests",
            "Query": "S4ServiceRequests"
        },
        {
            "Name": "S4ServiceRequestTranHistories",
            "Query": "S4ServiceRequestTranHistories"
        },
        {
            "Name": "SalesAreas",
            "Query": "SalesAreas"
        },
        {
            "Name": "SalesGroups",
            "Query": "SalesGroups"
        },
        {
            "Name": "SalesOffices",
            "Query": "SalesOffices"
        },
        {
            "Name": "SalesOrgs",
            "Query": "SalesOrgs"
        },
        {
            "Name": "SalesRespOrgs",
            "Query": "SalesRespOrgs"
        },
        {
            "Name": "SAPUsers",
            "Query": "SAPUsers"
        },
        {
            "Name": "ScheduleLines",
            "Query": "ScheduleLines"
        },
        {
            "Name": "SearchConditions",
            "Query": "SearchConditions"
        },
        {
            "Name": "SearchTypes",
            "Query": "SearchTypes"
        },
        {
            "Name": "ServiceAvailabilityProfiles",
            "Query": "ServiceAvailabilityProfiles"
        },
        {
            "Name": "ServiceImpactSet",
            "Query": "ServiceImpactSet"
        },
        {
            "Name": "ServiceItemCatDetermineSet",
            "Query": "ServiceItemCatDetermineSet"
        },
        {
            "Name": "ServiceItemCategories",
            "Query": "ServiceItemCategories"
        },
        {
            "Name": "ServiceItemCategorySchemas",
            "Query": "ServiceItemCategorySchemas"
        },
        {
            "Name": "ServiceNoteTypes",
            "Query": "ServiceNoteTypes"
        },
        {
            "Name": "ServiceOrgs",
            "Query": "ServiceOrgs"
        },
        {
            "Name": "ServicePriorities",
            "Query": "ServicePriorities"
        },
        {
            "Name": "ServiceProcessTypes",
            "Query": "ServiceProcessTypes"
        },
        {
            "Name": "ServiceResponseSchemas",
            "Query": "ServiceResponseSchemas"
        },
        {
            "Name": "ServiceRespOrgs",
            "Query": "ServiceRespOrgs"
        },
        {
            "Name": "ServiceTypes",
            "Query": "ServiceTypes"
        },
        {
            "Name": "ServiceUrgencySet",
            "Query": "ServiceUrgencySet"
        },
        {
            "Name": "ServiceValuationTypes",
            "Query": "ServiceValuationTypes"
        },
        {
            "Name": "ShippingPoints",
            "Query": "ShippingPoints"
        },
        {
            "Name": "SpecialStockTexts",
            "Query": "SpecialStockTexts"
        },
        {
            "Name": "StagingAreas",
            "Query": "StagingAreas"
        },
        {
            "Name": "StandardTextKeys",
            "Query": "StandardTextKeys"
        },
        {
            "Name": "StockTransportOrderHeaderLongTexts",
            "Query": "StockTransportOrderHeaderLongTexts"
        },
        {
            "Name": "StockTransportOrderHeaders",
            "Query": "StockTransportOrderHeaders"
        },
        {
            "Name": "StockTransportOrderItems",
            "Query": "StockTransportOrderItems"
        },
        {
            "Name": "StockTransportOrderSerialNumbers",
            "Query": "StockTransportOrderSerialNumbers"
        },
        {
            "Name": "StorageBins",
            "Query": "StorageBins"
        },
        {
            "Name": "StorageLocations",
            "Query": "StorageLocations"
        },
        {
            "Name": "STOScheduleLines",
            "Query": "STOScheduleLines"
        },
        {
            "Name": "SurveyAnswers",
            "Query": "SurveyAnswers"
        },
        {
            "Name": "SurveyDefinitions",
            "Query": "SurveyDefinitions"
        },
        {
            "Name": "SurveyDetCriterias",
            "Query": "SurveyDetCriterias"
        },
        {
            "Name": "SurveyDeterminations",
            "Query": "SurveyDeterminations"
        },
        {
            "Name": "SurveyItems",
            "Query": "SurveyItems"
        },
        {
            "Name": "SurveyLists",
            "Query": "SurveyLists"
        },
        {
            "Name": "SurveyQuestions",
            "Query": "SurveyQuestions"
        },
        {
            "Name": "SurveySections",
            "Query": "SurveySections"
        },
        {
            "Name": "SystemStatuses",
            "Query": "SystemStatuses"
        },
        {
            "Name": "UsageUoMs",
            "Query": "UsageUoMs"
        },
        {
            "Name": "UserFeatures",
            "Query": "UserFeatures"
        },
        {
            "Name": "UserGeneralInfos",
            "Query": "UserGeneralInfos"
        },
        {
            "Name": "UserLocations",
            "Query": "UserLocations"
        },
        {
            "Name": "UserObjectTypes",
            "Query": "UserObjectTypes"
        },
        {
            "Name": "UserPersonas",
            "Query": "UserPersonas"
        },
        {
            "Name": "UserPreferences",
            "Query": "UserPreferences"
        },
        {
            "Name": "UserRoles",
            "Query": "UserRoles"
        },
        {
            "Name": "UserStatuses",
            "Query": "UserStatuses"
        },
        {
            "Name": "UserSystemInfos",
            "Query": "UserSystemInfos"
        },
        {
            "Name": "UserTimeEntries",
            "Query": "UserTimeEntries"
        },
        {
            "Name": "UserTrunkAssignments",
            "Query": "UserTrunkAssignments"
        },
        {
            "Name": "ValuationTypes",
            "Query": "ValuationTypes"
        },
        {
            "Name": "VarianceReasons",
            "Query": "VarianceReasons"
        },
        {
            "Name": "Vendors",
            "Query": "Vendors"
        },
        {
            "Name": "VendorsCompanyData",
            "Query": "VendorsCompanyData"
        },
        {
            "Name": "VendorsPurchaseOrgData",
            "Query": "VendorsPurchaseOrgData"
        },
        {
            "Name": "WarehouseActivityAreas",
            "Query": "WarehouseActivityAreas"
        },
        {
            "Name": "WarehouseExceptionCodes",
            "Query": "WarehouseExceptionCodes"
        },
        {
            "Name": "WarehouseGoodsReceipts",
            "Query": "WarehouseGoodsReceipts"
        },
        {
            "Name": "WarehouseInboundDeliveries",
            "Query": "WarehouseInboundDeliveries"
        },
        {
            "Name": "WarehouseInboundDeliveryItems",
            "Query": "WarehouseInboundDeliveryItems"
        },
        {
            "Name": "WarehouseInboundDeliveryItemSerials",
            "Query": "WarehouseInboundDeliveryItemSerials"
        },
        {
            "Name": "WarehouseMovementReasons",
            "Query": "WarehouseMovementReasons"
        },
        {
            "Name": "WarehouseNums",
            "Query": "WarehouseNums"
        },
        {
            "Name": "WarehouseOrderQueues",
            "Query": "WarehouseOrderQueues"
        },
        {
            "Name": "WarehouseOrders",
            "Query": "WarehouseOrders"
        },
        {
            "Name": "WarehousePackagingMaterials",
            "Query": "WarehousePackagingMaterials"
        },
        {
            "Name": "WarehousePhysicalInventories",
            "Query": "WarehousePhysicalInventories"
        },
        {
            "Name": "WarehousePhysicalInventoryItems",
            "Query": "WarehousePhysicalInventoryItems"
        },
        {
            "Name": "WarehousePhysicalInventoryItemSerials",
            "Query": "WarehousePhysicalInventoryItemSerials"
        },
        {
            "Name": "WarehousePhysicalInventoryProcedures",
            "Query": "WarehousePhysicalInventoryProcedures"
        },
        {
            "Name": "WarehousePickHUs",
            "Query": "WarehousePickHUs"
        },
        {
            "Name": "WarehouseProcessCategories",
            "Query": "WarehouseProcessCategories"
        },
        {
            "Name": "WarehouseProcessTypes",
            "Query": "WarehouseProcessTypes"
        },
        {
            "Name": "WarehouseProductBatches",
            "Query": "WarehouseProductBatches"
        },
        {
            "Name": "WarehouseProductUoMs",
            "Query": "WarehouseProductUoMs"
        },
        {
            "Name": "WarehouseResources",
            "Query": "WarehouseResources"
        },
        {
            "Name": "WarehouseStockTypes",
            "Query": "WarehouseStockTypes"
        },
        {
            "Name": "WarehouseStorageBins",
            "Query": "WarehouseStorageBins"
        },
        {
            "Name": "WarehouseStorageBinTypes",
            "Query": "WarehouseStorageBinTypes"
        },
        {
            "Name": "WarehouseStorageSections",
            "Query": "WarehouseStorageSections"
        },
        {
            "Name": "WarehouseStorageTypes",
            "Query": "WarehouseStorageTypes"
        },
        {
            "Name": "WarehouseTaskConfirmations",
            "Query": "WarehouseTaskConfirmations"
        },
        {
            "Name": "WarehouseTaskConfSerialNumbers",
            "Query": "WarehouseTaskConfSerialNumbers"
        },
        {
            "Name": "WarehouseTasks",
            "Query": "WarehouseTasks"
        },
        {
            "Name": "WarehouseTaskSerialNumbers",
            "Query": "WarehouseTaskSerialNumbers"
        },
        {
            "Name": "WarrantyProfiles",
            "Query": "WarrantyProfiles"
        },
        {
            "Name": "WCMApplicationAttachments",
            "Query": "WCMApplicationAttachments"
        },
        {
            "Name": "WCMApplicationDocuments",
            "Query": "WCMApplicationDocuments"
        },
        {
            "Name": "WCMApplicationLongtexts",
            "Query": "WCMApplicationLongtexts"
        },
        {
            "Name": "WCMApplicationOrders",
            "Query": "WCMApplicationOrders"
        },
        {
            "Name": "WCMApplicationPartners",
            "Query": "WCMApplicationPartners"
        },
        {
            "Name": "WCMApplications",
            "Query": "WCMApplications"
        },
        {
            "Name": "WCMApplicationUsages",
            "Query": "WCMApplicationUsages"
        },
        {
            "Name": "WCMApprovalApplications",
            "Query": "WCMApprovalApplications"
        },
        {
            "Name": "WCMApprovalAttachments",
            "Query": "WCMApprovalAttachments"
        },
        {
            "Name": "WCMApprovalLongtexts",
            "Query": "WCMApprovalLongtexts"
        },
        {
            "Name": "WCMApprovalOrders",
            "Query": "WCMApprovalOrders"
        },
        {
            "Name": "WCMApprovalPartners",
            "Query": "WCMApprovalPartners"
        },
        {
            "Name": "WCMApprovalProcesses",
            "Query": "WCMApprovalProcesses"
        },
        {
            "Name": "WCMApprovalProcessLongtexts",
            "Query": "WCMApprovalProcessLongtexts"
        },
        {
            "Name": "WCMApprovalProcessSegments",
            "Query": "WCMApprovalProcessSegments"
        },
        {
            "Name": "WCMApprovals",
            "Query": "WCMApprovals"
        },
        {
            "Name": "WCMCatalogLongtexts",
            "Query": "WCMCatalogLongtexts"
        },
        {
            "Name": "WCMCatalogs",
            "Query": "WCMCatalogs"
        },
        {
            "Name": "WCMConflictRules",
            "Query": "WCMConflictRules"
        },
        {
            "Name": "WCMDocumentHeaderAttachments",
            "Query": "WCMDocumentHeaderAttachments"
        },
        {
            "Name": "WCMDocumentHeaderLongtexts",
            "Query": "WCMDocumentHeaderLongtexts"
        },
        {
            "Name": "WCMDocumentHeaderPartners",
            "Query": "WCMDocumentHeaderPartners"
        },
        {
            "Name": "WCMDocumentHeaders",
            "Query": "WCMDocumentHeaders"
        },
        {
            "Name": "WCMDocumentItemAttachments",
            "Query": "WCMDocumentItemAttachments"
        },
        {
            "Name": "WCMDocumentItemLongtexts",
            "Query": "WCMDocumentItemLongtexts"
        },
        {
            "Name": "WCMDocumentItems",
            "Query": "WCMDocumentItems"
        },
        {
            "Name": "WCMDocumentTechnicalObjects",
            "Query": "WCMDocumentTechnicalObjects"
        },
        {
            "Name": "WCMDocumentUsages",
            "Query": "WCMDocumentUsages"
        },
        {
            "Name": "WCMItemCategories",
            "Query": "WCMItemCategories"
        },
        {
            "Name": "WCMModelTypes",
            "Query": "WCMModelTypes"
        },
        {
            "Name": "WCMObjectApprovals",
            "Query": "WCMObjectApprovals"
        },
        {
            "Name": "WCMObjectLists",
            "Query": "WCMObjectLists"
        },
        {
            "Name": "WCMObjects",
            "Query": "WCMObjects"
        },
        {
            "Name": "WCMOpConditions",
            "Query": "WCMOpConditions"
        },
        {
            "Name": "WCMOpGroups",
            "Query": "WCMOpGroups"
        },
        {
            "Name": "WCMPartnerFunctions",
            "Query": "WCMPartnerFunctions"
        },
        {
            "Name": "WCMPermitCategories",
            "Query": "WCMPermitCategories"
        },
        {
            "Name": "WCMPhysicalBlockingTypes",
            "Query": "WCMPhysicalBlockingTypes"
        },
        {
            "Name": "WCMPrintFormatTags",
            "Query": "WCMPrintFormatTags"
        },
        {
            "Name": "WCMRequirements",
            "Query": "WCMRequirements"
        },
        {
            "Name": "WCMSwitchingDatas",
            "Query": "WCMSwitchingDatas"
        },
        {
            "Name": "WCMSystemStatuses",
            "Query": "WCMSystemStatuses"
        },
        {
            "Name": "WCMUserStatuses",
            "Query": "WCMUserStatuses"
        },
        {
            "Name": "WCMWorkReqTexts",
            "Query": "WCMWorkReqTexts"
        },
        {
            "Name": "WorkCenters",
            "Query": "WorkCenters"
        },
        {
            "Name": "WorkOrderHistories",
            "Query": "WorkOrderHistories"
        },
        {
            "Name": "WorkOrderHistoryTexts",
            "Query": "WorkOrderHistoryTexts"
        },
        {
            "Name": "WorkOrderOperationPhaseControls",
            "Query": "WorkOrderOperationPhaseControls"
        },
        {
            "Name": "WorkOrderPhaseControls",
            "Query": "WorkOrderPhaseControls"
        },
        {
            "Name": "WorkOrderTransfers",
            "Query": "WorkOrderTransfers"
        },
        {
            "Name": "WorkRequestConsequences",
            "Query": "WorkRequestConsequences"
        }
    ],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/ZEquinorSSAM/Actions/DEST_SAM2511_PPROP/Service/SyncFailureMessage.action",
    "OnSuccess": "/ZEquinorSSAM/Rules/DEST_SAM2511_PPROP/ErrorArchive_CheckForSyncError.js"
}