{
    "_Type" : "Action.Type.Filter",
    "PageToOpen" : "/SAPAssetManager/Pages/EWM/WarehouseTasks/WarehouseTaskSearchFilter.page",
    "Filterable" : "#Page:WarehouseOrderTaskList/#Control:SectionedTable",
    "ActionResult": {
        "_Name": "filterResult"
    }
}