{
    "_Type": "Action.Type.Navigation",
    "PageToOpen": "/SAPAssetManager/Pages/WorkOrders/SubOperation/MyWorkSubOperationsListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/WorkOrders/SubOperations/MyWorkSubOperationsListPageMetadata.js"
}