{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/WorkOrders/SubOperation/SubOperationsListView.page",
    "PageMetadata": "/SAPAssetManager/Rules/WorkOrders/SubOperations/SubOperationsListPageMetadata.js"
}