{
    "Actions": [
        "/SAPAssetManager/Actions/WorkOrders/SubOperations/SubOperationCreateUpdateNav.action"
    ],
    "OnSuccess": "/SAPAssetManager/Rules/WorkOrders/SubOperations/CreateUpdate/CreateSubOperationMobileStatus.js",
    "Target": {
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "_Type": "Action.Type.ODataService.ChangeSet"
}