{
	"_Type": "Action.Type.Navigation",
	"PageToOpen": "/SAPAssetManager/Pages/Inventory/Stock/StockDetails.page",
	"PageMetadata": "/SAPAssetManager/Rules/Inventory/Stock/StockDetailsPageMetadata.js"
}